chore: Update README.md
Helm 3.9 has a problem of templating. Since the latest version is 3.15 now, let's bump the minimum requirement.

```
Error: parse error at (risingwave/charts/common/templates/_resources.tpl:15): unclosed action
```